services:
  pissbot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pissbot
    volumes:
      - ./:/var/www/bot
    # command: php Bot.php
    restart: always
    privileged: true
